#Container for local testing.
version: "3"

services:

  db_test:
    container_name: "db_test"
    image: postgres:13.9
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
