#Containers to run the application and external database.
version: "3"

services:

  fastapi:
      container_name: fastapi_app
      build: .
      env_file:
          - .env
      command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      working_dir: /source/
      volumes:
          - .:/source/
      ports:
          - "8000:8000"
      depends_on:
          - production_db

  production_db:
      container_name: "production_db"
      image: postgres:13.9
      volumes:
          - postgres_data:/var/lib/postgresql/data/
      env_file:
          - .env
      ports:
          - "5432:5432"

volumes:
  postgres_data:
